export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const ADD_SUB_PROJECT = 'ADD_SUBPROJECT';
export const EDIT_SUB_PROJECT = 'EDIT_SUBPROJECT';
export const ADD_TIME_SLOT = 'ADD_TIME_SLOT';
export const EDIT_TIME_SLOT = 'EDIT_TIMESLOT';
export const CLEAR_TIME_SLOTS = 'CLEAR_TIMESLOTS';
export const WEEK_CHANGE = 'WEEK_CHANGE';
