export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_TIME_SLOT = 'ADD_TIME_SLOT';
export const MOVE_TIME_SLOT = 'MOVE_TIME_SLOT';
export const SET_DURATION_TIME_SLOT = 'SET_DURATION_TIME_SLOT';
export const SET_START_HOUR_TIME_SLOT = 'SET_START_HOUR_TIME_SLOT';
