export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const ADD_SUB_PROJECT = 'ADD_SUBPROJECT';
export const EDIT_SUB_PROJECT = 'EDIT_SUBPROJECT';
export const ADD_TIME_SLOT = 'ADD_TIME_SLOT';
export const MOVE_TIME_SLOT = 'MOVE_TIME_SLOT';
export const SET_DURATION_TIME_SLOT = 'SET_DURATION_TIME_SLOT';
export const SET_START_HOUR_TIME_SLOT = 'SET_START_HOUR_TIME_SLOT';
